bonxai_server_node:
  ros__parameters:
    resolution: 0.02
    frame_id: "map"
    base_frame_id: "base_footprint"

    occupancy_min_z: -100.0
    occupancy_max_z: 100.0

    sensor_model:
      max_range: -1.0
      hit: 0.7
      miss: 0.4
      min: 0.12
      max: 0.97

    latch: false

    filter:
      window_frames: 32      # size of sliding temporal window (frames, 1..64)
      required_observations: 3  # bits (distinct frames) required within window for promotion
      min_neighbor_support: 1   # require this many occupied/staged neighbors (0 disables spatial gating)
      stale_frames: 64       # drop staged voxel if not re-seen within this many frames
      deoccupy_frames: 0     # if >0, decay occupied voxels not reconfirmed within this many frames
      fractional_hits: true  # accumulate fractional log-odds while staged before promotion

